config/routes.rb
Rails.application.routes.draw do
  # 認証
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # リソース
  resources :users, only: [:show]
  resources :search, only: [:index]
  resources :reading_logs, only: [:create, :update, :destroy]
  resource :mypage, only: [:show] do
    get :home  # /mypage/home
    get :favorites, path: 'favorite_authors'  # /mypage/favorite_authors
    get :citations  # /mypage/citations
  end
  resources :books, only: [:index, :show, :update]
  resources :reading_logs, only: [] do
    resources :citations, only: [:create, :destroy]
  end
  resources :authors, only: [:show]
  resources :favorite_authors, only: [:create, :destroy]

  # 静的ページ
  get 'static/terms' => "static#terms", as: :terms
  get 'static/privacy' => "static#privacy", as: :privacy
  get 'static/about' => "static#about", as: :about

  # その他カスタムルート
  get 'home/index' => 'home#index'
  get  'contact',      to: 'contacts#new', as: :contact
  post 'contact/send', to: 'contacts#create'

  # ルートパス
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # ヘルスチェック
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  patch 'reading_logs/:id/update_status', to: 'reading_logs#update_status', as: :update_reading_status
  patch 'reading_logs/:id/update_comment', to: 'reading_logs#update_comment', as: :update_comment_reading_log

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # 本との関連
  has_many :authorships, dependent: :destroy
  has_many :books, through: :authorships

  # お気に入り著者との関連
  has_many :favorite_authors, dependent: :destroy
  has_many :users, through: :favorite_authors
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  validates :google_id, uniqueness: true
  validates :published_date, presence: false
  
  # 著者との関連
  has_many :authorships, dependent: :destroy
  # 中間テーブルのauthorshipテーブルを通してauthorを参照
  has_many :authors, through: :authorships

  # 読書ログとの関連
  has_many :reading_logs, dependent: :destroy
  has_many :users, through: :reading_logs

  # @book.save! が別のとこで走っても、既存の出版年を nil に上書きしない
  before_update :protect_published_date

  # published_date の setter をオーバーライド
  def published_date=(value)
    Rails.logger.debug "📥 setter called with: #{value.inspect} (#{value.class})"

    if value.is_a?(String)
      normalized = case value
                  when /^\d{4}$/ then "#{value}-01-01"
                  when /^\d{4}-\d{2}$/ then "#{value}-01"
                  else value
                  end

      begin
        super(Date.parse(normalized)) # StringをDateに変換して保存
      rescue ArgumentError
        Rails.logger.warn "⚠️ setter: 日付のパース失敗 → nil"
        super(nil)
      end
    else
      super(value) # すでに Date 型などの場合はそのまま
    end
  end

  private

  # 保存済みのpublished_dateがある場合、それを消さないように保護
  def protect_published_date
    if published_date_changed? && published_date_was.present? && published_date.blank?
      self.published_date = published_date_was
    end
  end
end

app/models/citation.rb
class Citation < ApplicationRecord
  belongs_to :reading_log

  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/favorite_author.rb
class FavoriteAuthor < ApplicationRecord
  belongs_to :user
  belongs_to :author
end

app/models/reading_log.rb
class ReadingLog < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :citations, dependent: :destroy
  validates :book_id, uniqueness: { scope: :user_id }
  accepts_nested_attributes_for :citations

  enum reading_status: { read: 0, unread: 1, stacked: 2 }

  before_save :set_read_at_if_just_became_read

  def reading_status_label
    case reading_status
    when "read"
      "既読"
    when "unread"
      "未読"
    when "stacked"
      "積読"
    else
      "未設定"
    end
  end

  private

  def set_read_at_if_just_became_read
    if reading_status_changed? && read?
      self.read_at = Time.current
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  
  validates :nickname, presence: true
  validates :email, uniqueness: true
  validate :avatar_format

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # 読書ログとの関連
  has_many :reading_logs, dependent: :destroy
  has_many :books, through: :reading_logs

  # お気に入り著者との関連
  has_many :favorite_authors, dependent: :destroy
  has_many :authors, through: :favorite_authors

  def send_password_change_notification?
    true
  end

  private

  def avatar_format
    return unless avatar.attached?
    unless avatar.content_type.in?(%w[image/png image/jpg image/jpeg])
      errors.add(:avatar, "はJPEGまたはPNG形式でアップロードしてください")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  end

  def show
    @book = Book.find(params[:id])
    @reading_log = current_user.reading_logs.find_by(book_id: @book.id)
    @book.published_date = Date.parse(@book.published_date) if @book.published_date.is_a?(String)
  end

  def update
    @book = Book.find(params[:id])

    year_param  = params[:published_date_year]
    month_param = params[:published_date_month]

    if year_param.blank? || month_param.blank?
      flash.now[:alert] = "出版年と月は必須です。"
      render :show and return
    end

    year  = year_param.to_i
    month = month_param.to_i
    day   = (params[:published_date_day].presence || "1").to_i

    begin
      @book.published_date = Date.new(year, month, day)
    rescue ArgumentError
      flash.now[:alert] = "無効な日付です。"
      render :show and return
    end

    if @book.save
      redirect_to @book, notice: "出版年を登録しました！"
    else
      render :edit
    end
  end

  private

  def book_params
    permitted = params.require(:book).permit(:published_date)
    Rails.logger.debug("📦 book_params: #{permitted.inspect}")
    permitted
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # ビューからリクエストを受け取り、空文字ならエラーを返し、そうでなければBookSearchServiceを呼び出す
  def index
    if params[:q].blank?
      flash.now[:search_error] = '！入力してください'
      @google_books = []
    else
      @google_books = BookSearchService.new(params[:q]).call
      create_books_from_api_data(@google_books)
    end
  end

  private

  # BookSearchServiceが返した本の情報をDBに保存
  def create_books_from_api_data(books_data)
    books_data.each do |data|
      book = Book.find_or_initialize_by(google_id: data[:google_id])

      book.assign_attributes(
        title: data[:title],
        thumbnail_link: data[:thumbnail_link],
        description: data[:description],
        isbn: data[:isbn]
      )

      # setterが自動で正規化してくれる
      book.published_date = data[:published_date] if data[:published_date].present? && book.published_date.blank?

      book.save!

      # 著者情報の保存（重複追加を防止）
      # TODO 著者が3名以上の場合、最初の2名のみ表示して残りは「他」とする
      data[:authors].each do |author_name|
        author = Author.find_or_create_by!(name: author_name)
        book.authors << author unless book.authors.include?(author)
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/reading_logs_helper.rb
module ReadingLogsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% provide :body_class, "is-home" %>
<% provide :in_main_footer, render("shared/footer") %>

<%# home-kv %>
<div class="home-kv home-scroll-snap">
  <div class="home-kv__inner">
    <%= image_tag "img-home-kv.jpg", class: "home-kv__img", alt: "コンクリート壁の静かげな空間で1冊の見開きの本が置かれている写真" %>

    <div class="home-kv__overlay">
      <h1 class="home-kv__title">読綴<span class="home-kv__subtitle">-Yomitsuzuri-</span></h1>
      <p class="home-kv__catch-copy">ことばに、わたしが映る。</p>
    </div>
  </div>
</div>
<%# home-kv end %>

<%# home-about %>
<section class="home-about home-scroll-snap js-fade-in">
  <div class="home-about__inner l-container--m l-section--l">
    <h2 class="c-title-home">
      わたしだけの読書録
    </h2>
    <p class="home-about__intro">
      <p class="home-about__text">
        <span class="home-about__span">読綴は、自分自身と静かに向き合うための</span>
        <span class="home-about__span">著者フォーカス型 読書記録アプリです。</span>
      </p>
      <p class="home-about__text">
        <span class="home-about__span">好きな著者の歩みを辿るように、</span>
        <span class="home-about__span">その作品たちと、ひとつずつ向き合っていく。</span>
      </p>
      <p class="home-about__text">
        <span class="home-about__span">うまく書こうとしなくていい。</span>
        <span class="home-about__span">きれいじゃなくていい。</span>
      </p>
      <p class="home-about__text">
        <span class="home-about__span">心に残ったことばを、わたしの感性で、</span>
        <span class="home-about__span">ありのままに綴る。</span>
      </p>
      <p class="home-about__text">
        <span class="home-about__span">評価も、いいねも、ここにはありません。</span>
        <span class="home-about__span">あるのはただ、本と、わたしの感性だけ。</span>
      </p>
    </p>
  </div>
</section>
<%# home-about end %>

<%# home-how-to %>
<section class="home-how-to home-scroll-snap js-fade-in">
  <div class="home-how-to__inner l-container--m l-section--l">
    <h2 class="c-title-home">わたしと本のための機能</h2>

    <ul class="home-how-to__list">
      <li class="home-how-to__item">
        <h3 class="home-how-to__title">本と向き合う</h3>
        <%= image_tag "pic-home-how-to-book.png", class: "home-how-to__img", alt: "作品ページのスクリーンショット。本の情報が表示され、引用やコメントなどを登録できます。" %>
        <p class="home-how-to__description">
          <span class="home-how-to__span home-how-to__span--small">※著作権保護のため一部内容をぼかして表示しています。</span>
          <span class="home-how-to__span">感じたこと、引用を自由に記録。</span>
          <span class="home-how-to__span">共有機能はなく、自分だけのために。</span>
        </p>
      </li>
      <li class="home-how-to__item">
        <h3 class="home-how-to__title">著者と向き合う</h3>
        <%= image_tag "pic-home-how-to-author.png", class: "home-how-to__img", alt: "著者ページのスクリーンショット。登録した作品の読了率がバーで表示され、作品が年代ごとに並びます。" %>
        <p class="home-how-to__description">
          <span class="home-how-to__span">好きな著者の作品年表を自分の手で作成。</span>
          <span class="home-how-to__span">読了率・既読 / 未読 / 積読がひと目でわかる。</span>
        </p>
      </li>
      <li class="home-how-to__item">
        <h3 class="home-how-to__title">ことばと向き合う</h3>
        <%= image_tag "pic-home-how-to-citation.png", class: "home-how-to__img", alt: "引用一覧ページのスクリーショット。登録した全ての引用を一覧で見ることができます。" %>
        <p class="home-how-to__description">
          <span class="home-how-to__span">残してきたことばを一覧で振り返る。</span>
          <span class="home-how-to__span">自分の思考の軌跡を辿る。</span>
        </p>
      </li>
    </ul>
  </div>
</section>
<%# home-how-to end %>

<%# home-search %>
<section class="home-search home-scroll-snap js-fade-in">
  <div class="home-search__inner l-container--m l-section--l">
    <h2 class="c-title-home">
      好きな本を探してみる
    </h2>
    
    <%# 検索フォーム %>
    <div class="c-search__wrap">
      <%= form_with(
            url: search_index_path,
            method: :get,
            local: true,
            class: "c-search__form",
            data: { mode: "inline" }
          ) do |form| %>
        <div class="c-search c-search--center">
          <%= form.text_field :q,
              placeholder: "タイトル・著者名など",
              class: "c-search__text-field" %>
          <div class="c-search__warning-wrap">
            <div class="c-search__warning is-hidden">！入力してください</div>
          </div>
          <%= button_tag(type: "submit", class: "c-search__submit-btn") do %>
            <svg role="img" xmlns="http://www.w3.org/2000/svg" width="32px" height="32px" viewBox="0 0 24 24" aria-labelledby="searchIconTitle" stroke="#3e3e3e" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="#3e3e3e"> <title id="searchIconTitle">検索</title> <path d="M14.4121122,14.4121122 L20,20"/> <circle cx="10" cy="10" r="6"/> </svg>
          <% end %>
        </div>
      <% end %>
    </div>
    <%# 検索フォーム end %>

    <p class="home-search__lead">
      <span class="home-search__span">気になる本が見つかったら、</span>
      <span class="home-search__span">あなたの読書録を始めてみませんか。</span>
    </p>

    <div class="home-search__cta-wrap">
      <%= link_to "記録を始める", new_user_registration_path, class: "home-search__cta" %>
    </div>
  </div>

  <div class="home-footer">
    <%= yield :in_main_footer %>
  </div>
</section>
<%# home-search end %>

app/views/search/index.html.erb
<% content_for :title, "検索結果 - Yomitsuzuri" %>
<% content_for :description, "入力したキーワードから著者や作品を検索し、該当する本や著者ページにすぐアクセスできます。" %>
<% content_for :og_title, "検索結果 - Yomitsuzuri" %>
<% content_for :og_description, "入力したキーワードから著者や作品を検索し、該当する本や著者ページにすぐアクセスできます。" %>
<% content_for :og_type, "article" %>

<div class="l-container--l l-section">
  <h1 class="search-result__title">
    「<%= params[:q] %>」の検索結果
  </h1>

  <div class="l-section-body">
    <% if @google_books.present? %>
      <ul class="c-works c-works--5columns">
        <% @google_books.each do |book| %>
          <li class="c-works__item c-works__item--5columns">
            <%# サムネ画像がない場合は代替画像を表示 %>
            <% image_url = book[:thumbnail_link] %>
            <img class="c-works__image c-works__image--5columns" src="<%= image_url.start_with?("http") ? image_url : asset_path(image_url) %>" alt="<%= book[:title].to_s %> の表紙画像">

            <div class="c-works__info c-works__info--5columns">
              <div class="c-works__text c-works__text--5columns">
                <h2 class="c-works__title c-works__title--5columns"><%= book[:title] %></h2>
                <p class="c-works__author c-works__author--5columns">
                  <%= book[:authors].join(", ") %>
                </p>
                <p class="c-works__published_date c-works__published_date--5columns">
                  <%= book[:published_date] %>
                </p>
              </div>

              <%# ログイン時は登録用モーダル、ログアウト時はログインページに遷移 %>
              <% if user_signed_in? %>
                <%# DBに保存するデータをボタンに埋め込む %>
                <button type="button" class="c-register-modal__open c-works__btn--5columns c-button c-button--small c-button--white"
                        data-book-id="<%= book[:isbn] %>"
                        data-book-title="<%= book[:title] %>"
                        data-book-authors="<%= book[:authors].join(', ') %>"
                        data-book-image="<%= image_url.start_with?("http") ? image_url : asset_path(image_url) %>"
                        data-book-google-id="<%= book[:google_id] %>"
                        data-book-published-date="<%= book[:published_date] %>"
                        data-book-description="<%= book[:description] %>" >
                  作品を登録
                </button>
              <% else %>
                <%= link_to "作品を登録",
                    new_user_session_path,
                    class: "c-works__btn--5columns c-button c-button--small c-button--white" %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>該当する本は見つかりませんでした。</p>
    <% end %>
  </div>

  <%# 作品登録モーダル %>
  <div class="c-register-modal is-hidden">
    <div class="c-register-modal__wrap">
      <h2 class="c-register-modal__title">作品を登録</h2>

      <%# 登録ボタンに埋め込んだ情報をjsで差し込む %>
      <div class="c-register-modal__book-info">
        <p class="c-register-modal__book-title"></p>
        <p class="c-register-modal__book-authors"></p>
      </div>

      <div class="c-register-modal__content">
        <img class="c-register-modal__book-image" src="" alt="本の表紙画像" />

        <%# 登録フォーム %>
        <%= form_with url: reading_logs_path,
                      method: :post,
                      local: false,
                      scope: :reading_log,
                      class: "c-register-modal__form" do |f| %>
          <%# 書籍情報を入力値と一緒に hidden で送る %>
          <%= hidden_field_tag :book_title %>
          <%= hidden_field_tag :book_authors %>
          <%= hidden_field_tag :book_published_date %>
          <%= hidden_field_tag :book_image_url %>
          <%= hidden_field_tag :book_google_id %>
          <%= hidden_field_tag :book_description %>
          <%= hidden_field_tag :isbn %>

          <div class="c-register-modal__textarea-wrap">
            <%= f.label :comment, "コメント", class: "c-register-modal__label" %>
            <%= f.text_area :comment,
                id: "comment",
                placeholder: "あなたの考えを記しておきましょう",
                class: "c-register-modal__textarea" %>
            <%# scopeにreading_logを設定しているので、name="reading_log[comment]"と同じ %>
          </div>

          <%= f.fields_for :citations do |cf| %>
            <div class="c-register-modal__textarea-wrap">
              <%= cf.label :content, "引用メモ", class: "c-register-modal__label" %>
              <%= cf.text_area :content,
                  id: "content",
                  placeholder: "心に残った文章を書き留めておきましょう",
                  class: "c-register-modal__textarea" %>

              <div class="c-register-modal__input-wrap">
                <%= cf.label :page_number, "ページ番号", class: "c-register-modal__label" %>
                <%= cf.text_field :page_number, id: "page_number", placeholder: "例：p.123", class: "c-register-modal__input" %>
              </div>
            </div>
          <% end %>
          
          <div>
            <%= f.label :reading_status, "読書状況", class: "c-register-modal__label" %>
            <div class="c-register-modal__select-wrap">
              <%= f.select :reading_status,
                            [["既読", 0], ["未読", 1], ["積読", 2]],
                            { prompt: "選択してください" },
                            class: "c-register-modal__status" %>
            </div>
          </div>
          <%= f.submit "登録する", class: "c-register-modal__submit c-button c-button--medium c-button--center c-button--white" %>
        <% end %>
        <%# 登録フォーム end %>

      </div>
      <button type="button" class="c-register-modal__close">閉じる</button>
    </div>
  </div>
</div>